<?php

namespace App\Services;

use App\Models\Alert;
use App\Models\IncidentTicket;
use App\Models\SecurityEvent;

class CorrelationEngine
{
    private const WINDOW_SECONDS = 60;

    private const THRESHOLD = 3;

    private const RULES = [
        'arp_spoof' => ['ruleName' => 'repeated_arp_spoof', 'label' => 'ARP spoofing'],
        'dns_poison' => ['ruleName' => 'repeated_dns_poison', 'label' => 'DNS poisoning'],
        'dos_attack' => ['ruleName' => 'repeated_dos_attack', 'label' => 'DoS attack'],
    ];

    public static function correlate(SecurityEvent $event): void
    {
        $rule = self::RULES[$event->eventType] ?? null;

        if ($rule === null) {
            return;
        }

        $windowStart = $event->created_at->copy()->subSeconds(self::WINDOW_SECONDS);

        $matches = SecurityEvent::where('eventType', $event->eventType)
            ->where('victimDeviceId', $event->victimDeviceId)
            ->whereBetween('created_at', [$windowStart, $event->created_at])
            ->get();

        if ($matches->count() < self::THRESHOLD) {
            return;
        }

        $matchedIds = $matches->pluck('id')->all();

        $existingAlert = Alert::where('ruleName', $rule['ruleName'])
            ->where('victimDeviceId', $event->victimDeviceId)
            ->where('status', 'open')
            ->first();

        if ($existingAlert) {
            $relatedEventIds = array_values(array_unique([
                ...$existingAlert->relatedEventIds,
                ...$matchedIds,
            ]));

            $existingAlert->relatedEventIds = $relatedEventIds;
            $existingAlert->eventCount = count($relatedEventIds);
            $existingAlert->description = sprintf(
                'Repeated %s detected against %s (%d events within %ds)',
                $rule['label'],
                $event->victimDeviceId,
                count($relatedEventIds),
                self::WINDOW_SECONDS,
            );
            $existingAlert->save();

            return;
        }

        $description = sprintf(
            'Repeated %s detected against %s (%d events within %ds)',
            $rule['label'],
            $event->victimDeviceId,
            count($matchedIds),
            self::WINDOW_SECONDS,
        );

        $alert = Alert::create([
            'ruleName' => $rule['ruleName'],
            'severity' => 'high',
            'victimDeviceId' => $event->victimDeviceId,
            'victimDeviceName' => $event->victimDeviceName,
            'relatedEventIds' => $matchedIds,
            'eventCount' => count($matchedIds),
            'description' => $description,
            'status' => 'open',
        ]);

        IncidentTicket::create([
            'title' => sprintf('%s burst on %s', $rule['label'], $event->victimDeviceName ?? $event->victimDeviceId),
            'description' => $description,
            'status' => 'open',
            'origin' => 'auto',
            'deviceName' => $event->victimDeviceName,
            'relatedAlertId' => (string) $alert->id,
            'auditLog' => [[
                'timestamp' => now()->toIso8601String(),
                'action' => 'created',
                'note' => 'Auto-generated by correlation engine',
            ]],
        ]);
    }
}
